version: "3.8"

services:
  frontend:
    container_name: react-vite
    build: ./frontend
    volumes:
      - ./frontend:/var/www/frontend
      - /var/www/frontend/node_modules
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
